### ISSUE TITLE
Create an about page with the following information

### ISSUE THREAD

**Issue by njk464** [samuelbraley/idb#10]
description of the site, its purpose, its intended users
the group name
the group members
for each member:
    name
    photo
    bio
    major responsibilities
    no. of commits
    no. of issues
    no. of unit tests
stats:
    total no. of commits
    total no. of issues
    total no. of unit tests
    a link to the Apiary API
    a link to the GitHub Issue Tracker
    a link to the GitHub Repo
data:
    links to the data sources
    description of how each was scraped
tools:
    tools used
    describe their use
    special focus on optional tools that were not required

**Comment by njk464** [comment]
Still need to add 

- links to the data sources and their descriptions
- tools used and descriptions of their use
- link to the report and travis ci

**Comment by tabenmalik** [comment]
About Page is completed.
