### ISSUE TITLE
Implement the Rest API

### ISSUE THREAD

**Issue by njk464** [samuelbraley/idb#40]
Implement ALL of the Rest API

**Comment by tabenmalik** [comment]
Rest API has been implemented with Flask-Restless. The API setup for the application happens in api.py. Documentation of Flask's API will come shortly on Apiary. However here is a quick breakdown of the calls you can make:

/api/v1/(plural of model)
This returns a collection of the model. Response is automatically paginated. Some fields can be added to change the response.
     page=(num)
     Returns the collection starting at the given page
     results_per_page=(num)
     Sets the number of objects per page. For now the upper limit is 50.

/api/vi/(plural of model)/(pid)
Returns an individual of a model

There is also searching and filtering built in to Restless so front end will not have to do that intensively. I will document those functions as well in Apiary
